[package]
name = "xi-web"
version = "0.1.0"
authors = ["Valencia <davidalencia@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "2.0"
actix-rt = "1"
actix-files = "0.2.1"
